# Generated by Django 2.1.4 on 2018-12-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('clima', models.CharField(max_length=80)),
                ('terreno', models.CharField(max_length=80)),
            ],
        ),
    ]
