# Generated by Django 2.1.4 on 2018-12-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeta',
            name='qtde_planeta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
