# Generated by Django 2.1.4 on 2018-12-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181215_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeta',
            name='clima',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='planeta',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='planeta',
            name='terreno',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
