# Generated by Django 2.1.4 on 2018-12-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181215_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeta',
            name='qtde_planetas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
